### ISSUE TITLE
Error compile. (small fix)

### ISSUE THREAD

**Issue by BobaFett58** [niesteszeck/ng2-material-bootstrap-wizard#1]
Hej, thanks for your work, this looks awesome, but I have a few things. First, it doesn't work on 'ng serve' (maybe it's only my problem), but its working on 'npm start'. And the second one, I can't compile the project, I have an error in the 'updatePicturePreview' function (wizard-form.component.ts). It's easy to fix, just change the return type to Promise<{}>; (I hope it's will work after this fix).
Best regards.

**Comment by niesteszeck** [comment]
Hi, thanks for reporting. First i haven't try the ng serve, just the npm start. This is a really at beta, because I extracted (from other big project) just the necessary code to make a repo for sharing.


the other problem, in wath situation do you have the error?
